### ISSUE TITLE
Does Not Seem To Be Compatible With Entities 0.50.0

### ISSUE THREAD

**Issue by CybeRockStudio** [felipemcoliveira/com.felipemcoliveira.crowdmorph#1]
hi there thank you for creating this package 

but it does not seem to be compatible with entities 0.50.0

**Comment by CybeRockStudio** [comment]
went through the updating guidelines and now I'm getting these two beautiful errors

1- ssets\CrowdMorph\com.felipemcoliveira.crowdmorph-master\Runtime\Core\CoreValidation.cs(55,63): error CS8377: The type 'T' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'


2-Assets\CrowdMorph\com.felipemcoliveira.crowdmorph-master\Runtime\Core\CoreValidation.cs(63,71): error CS8377: The type 'T' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'
![Capture](https://user-images.githubusercontent.com/50476385/177840375-11886c83-1186-499e-81e7-9b9a1bbb68da.PNG)

**Comment by CybeRockStudio** [comment]
for anyone who stumbles upon this simply change where T : struct to where T : unmanaged

**Comment by CybeRockStudio** [comment]
but i have to say i still had no luck making it work as there are many more bugs that popped up

**Comment by felipemcoliveira** [comment]
Hi @CybeRockStudio, Entities 0.50 has been released after CrowdMorph, so I didn't update it to support this version. I don't think it would be hard task to do it. maybe I'll try to make it work in 2 weeks. Thanks for your feedback.
